<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>MineHunter-cli</AssemblyName>
    <RootNamespace>MineHunter</RootNamespace>
    <UseWPF>false</UseWPF>
    <ApplicationManifest>$(MSBuildThisFileDirectory)../app.manifest</ApplicationManifest>
    <ApplicationIcon>$(MSBuildThisFileDirectory)../app.ico</ApplicationIcon>
    <AssemblyTitle>MineHunter command line</AssemblyTitle>
    <AutoGenerateBindingRedirects>false</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>false</GenerateBindingRedirectsOutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MineHunter.Core\MineHunter.Core.csproj" />
    <Reference Include="System.Management" />
    <Reference Include="System.Web.Extensions" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>
</Project>
