<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>MineHunter</AssemblyName>
    <RootNamespace>MineHunter</RootNamespace>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>$(MSBuildThisFileDirectory)../app.manifest</ApplicationManifest>
    <ApplicationIcon>$(MSBuildThisFileDirectory)../app.ico</ApplicationIcon>
    <AssemblyTitle>MineHunter</AssemblyTitle>
    <AutoGenerateBindingRedirects>false</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>false</GenerateBindingRedirectsOutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MineHunter.Core\MineHunter.Core.csproj" />
    <ProjectReference Include="..\MineHunter.UI\MineHunter.UI.csproj" />
    <Reference Include="System.Management" />
    <Reference Include="System.Web.Extensions" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="../LaunchGuard.cs" Link="LaunchGuard.cs" />
  </ItemGroup>
</Project>
